kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: image-validation-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: thin-csi
